// File generated by FlutterFire CLI.
// ============================================================
// Firebase project: maylaud-app
// Android app: Maylaud.Android (matches applicationId in
// android/app/build.gradle.kts — these must always stay in sync)
//
// Android only — no iOS app is registered in this Firebase project.
// If you add iOS support later, run flutterfire configure to add the
// iOS case back in rather than hand-editing this file.
// ============================================================
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run `flutterfire configure` to add it.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android in this '
          'project. Run `flutterfire configure` and register an iOS app '
          'first if you need iOS support.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-NQrn9gGJZlEGjMDZWrtBnSAwCowGTs',
    appId: '1:818537075259:android:8b5e7eb7d441eb183f421e',
    messagingSenderId: '818537075259',
    projectId: 'maylaud-app',
    storageBucket: 'maylaud-app.firebasestorage.app',
  );
}